### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by 3cooper** [ovr/phpsa#102]
When I run phpsa (  `>vendor/ovr/phpsa/bin/phpsa check file.php` ) I get the findings from the analysis but I also get lines saying: `fatal: Not a git repository (or any of the parent directories): .git`.  I am new to composer and phpsa so I could have something configured incorrectly.  Any help would be great.

**Comment by ddmler** [comment]
Try to remove your vendor directory and run composer install again.

**Comment by 3cooper** [comment]
I did, reinstalled composer, and then reinstalled phpsa and I still get the error.

``````
>git --version
git version 2.9.3

>php --version
PHP 5.5.36 (cli) (built: May 29 2016 01:07:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

>php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
>php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
>php composer-setup.php
>php -r "unlink('composer-setup.php');"

>php composer.phar require ovr/phpsa
``````

**Comment by ravage84** [comment]
This happened to me, too, but I didn't install it through Composer but used phpsa (0.5.0) as phar on my SVN working copy.

**Comment by 3cooper** [comment]
I just uninstalled the composer version and installed the phar version.  I get the same error.

```````
>phpsa check FormDataAdapter.inc 
fatal: Not a git repository (or any of the parent directories): .git

Notice:  Missing docblock for __construct() method in FormDataAdapter.inc on 78 [missing-docblock]

fatal: Not a git repository (or any of the parent directories): .git

Notice:  Missing docblock for %s() property in FormDataAdapter.inc on 13 [missing-docblock]

fatal: Not a git repository (or any of the parent directories): .git

Notice:  Missing docblock for %s() property in FormDataAdapter.inc on 14 [missing-docblock]

fatal: Not a git repository (or any of the parent directories): .git

Notice:  Please use [] (short syntax) for array definition. in FormDataAdapter.inc on 92 [array.short-syntax]

fatal: Not a git repository (or any of the parent directories): .git
...similar errors continue
```````

**Comment by ddmler** [comment]
Try to edit phpsa.yml config file and set blame to false. On true it executes git blame --show-email for every shown notice.

**Comment by 3cooper** [comment]
I am new to phar.  Where can i find the yml file?  I am on OS X.

**Comment by ddmler** [comment]
It's in the directory of phpsa. It's .phpsa.yml and it's a hidden file (because of the . in front) so you won't see it if you did not configure it. But the configuration there is not working at the moment.
For now try to do this:
```
vendor/ovr/phpsa/bin/phpsa check file.php --blame=false
```
This should remove the git error messages.

**Comment by 3cooper** [comment]
That did it.  Thanks.

**Comment by ddmler** [comment]
closed - not really a bug, blame will be default off with PR from K-Phoen
