### ISSUE TITLE
Old style constructors

### ISSUE THREAD

**Issue by K-Phoen** [ovr/phpsa#103]
PHPSA should warn about old style class constructors.

``` php
class Foo {
    public function Foo() {
    }
}
```

**Comment by ovr** [comment]
Rly cool idea 👍

**Comment by ddmler** [comment]
still needed:
- [ ] Refactor to work with ClassDefinition hasMethod()

**Comment by ovr** [comment]
> Refactor to work with ClassDefinition hasMethod()
@ddmler I will work on it

**Comment by tomzx** [comment]
If it's not already done, make sure you respect the rules specified by https://wiki.php.net/rfc/remove_php4_constructors, namely that it is legal to have a function with the same name as the class if there's a `__construct` defined.

**Comment by ddmler** [comment]
I think this would be a bit too much. If something has the same methodname as it's classname it probably violates either classname conventions or methodname conventions. So I would rather notice it even if it is ok.

**Comment by Kilgaloon** [comment]
I see there is analyzer OldConstructor, why is this still a thing? Is there anything to be done on this subject?

**Comment by ovr** [comment]
@Kilgaloon Nope, it's implemented by @ddmler in https://github.com/ovr/phpsa/pull/105
I am going to close
