### ISSUE TITLE
[Bug] FuncCall analyzers

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#113]
So when checking with phpsa:
```php
function a() {
return rand(1,10);
}
```
we get a notice: rand() is not recommended ...
and:
```php
function a() {
$b = rand(1,10);
}
```
we get again a notice: rand() is not recommended ...
whereas:
```php
function a() {
echo rand(1,10);
}
```
we get nothing.
and:
```php
<?php
rand(1,10);
```
we get nothing again.

The AST we get from php-parser is as follows:
return_object->expr = FuncCall_object
assign_object->expr = FuncCall_object
echo_object->exprs = array(FuncCall_object)
statements = array(FuncCall_object) //4th example above
so i guess we can't handle arrays?

**Comment by ovr** [comment]
@ddmler 

I think this caused because PHPSA doesn't support GLOBAL SCOPE for compiling in `Compiler` component
Current it's only `Function` or `Class`

**Comment by ddmler** [comment]
@ovr 
That would explain the 4th example but the 3rd with function and echo in it doesn't work too and here it is a function. :cry:

**Comment by ovr** [comment]
@ddmler related to 3rd I find a NFR on unimplemented `Echo_` compiler, start to work on it

**Comment by ovr** [comment]
@ddmler You was right related 3rd example, for now It's supporting in `master`
Related to https://github.com/ovr/phpsa/commit/19c440404ae570fb33a2b4d02bcdcb0bb13fe8c1

Thanks
