### ISSUE TITLE
[Analyzer][Easy] Don't use Goto

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#117]
This is an easy task suitable for someone who is new to this project. 
We need a Statement analyzer for: Node\Stmt\Goto_

Just copy an existing Statement analyzer and hook it up to the Goto_ node (1st argument of pass method and getRegister method)
All you have to do inside the pass method is create the notice and return true.
(Don't forget to add it to the factory and create 2 tests: one with goto and one without in analyzer-fixtures)

**Comment by ovr** [comment]
@ddmler Seems it's merged and implemented, should we close this issue?
Thanks

**Comment by ddmler** [comment]
@ovr yes issue can be closed.
