### ISSUE TITLE
[Docs] Start working on documentation

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#141]
- [x] Infos what does each component (Compiler, Analyzer, CFG, Definitions?)
- [x] Infos what each analyzer does
- [x] Infos on configuration (PR from @K-Phoen )
- [x] How to write an own analyzer?
- [x] Update Readme.md (make it shorter, link to docs and contributing guide)
- [x] Check spelling and grammar (we have no native english speaker currently, so this would be really appreciated)
- [ ] Just try some things out we are happy for every PR to docs :cake: 

What do you think? @ovr @K-Phoen 
I thought we'd do it like php-parser (doc directory)

**Comment by K-Phoen** [comment]
Great ideas :+1:

**Comment by tomzx** [comment]
I'd also suggest setting up a https://readthedocs.org/ for it. If you create a `docs` folder for it, it should automatically work out of the box without doing any configuration.

**Comment by chasingSublimity** [comment]
I'm happy to check spelling and grammar. Let me know if you have any specific areas in mind!

**Comment by K-Phoen** [comment]
I guess that the [contributing guide](https://github.com/ovr/phpsa/blob/master/.github/CONTRIBUTING.md), the [PR template](https://github.com/ovr/phpsa/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and [the documentation](https://github.com/ovr/phpsa/tree/master/docs) could benefit from this kind of check :)

**Comment by ddmler** [comment]
And the Contributing guide is a bit of a mess. So if someone wants to reorganize this and make it pretty, that would be great too :smile:

**Comment by chasingSublimity** [comment]
Awesome. I'm working on the Contributing guide now!

**Comment by chasingSublimity** [comment]
See [#187](https://github.com/ovr/phpsa/pull/187).

The biggest edit I made was adjusting the mood of your unordered lists from declarative ("we use ...") to imperative ("use xyz..."). If this does not adequately communicate your original intention, I'm happy to correct.

If the PR is satisfactory, I'll be happy to look at your PR template and Documentation as well.

**Comment by ddmler** [comment]
Thanks. If you want you can also check Readme and analyzer notice messages. In Readme "How to use" you see how the notice messages currently look like (examples).
For example some analyzers end their notice text with a dot but the sentence continues:
`You are trying to cast 'string' to 'string'. in fixtures/`

**Comment by chasingSublimity** [comment]
On it!

**Comment by ddmler** [comment]
@chasingSublimity I just added more documentation pages. If you want you can check these. :grin:

**Comment by ddmler** [comment]
done
