### ISSUE TITLE
[Analyzer] Assignment in condition

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#147]
We will need to check the conditions of If_, Elseif_, While_, For_, Do_ and maybe switch cases:
```php
switch (true) {
    case ($x = 1): // always true since it's an assignment, in contrast:
    case ($x == 1): // only if x is 1
}
```
Statement analyzer with multiple register.
For Hacktoberfest: This issue is a bit more work than the others. You should probably try another first and get familiar with the analyzer workflow here.

**Comment by nikhilsaldanha** [comment]
@ddmler I've added this feature for all statements except For_

I'm not sure how to do this for For_ statements since they normally involve assignments. Can I get a clarification on that?

**Comment by ddmler** [comment]
closed - merged with 191

**Comment by nikhilsaldanha** [comment]
@ddmler I forgot to handle for statements. That is handled by the PR that I just submitted.
