### ISSUE TITLE
[Analyzer] Don't use global

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#159]
It's bad practice to use global $a; or something like that.
So we need a statement analyzer for Global_ Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/DoNotUseGoto.php )
and register it to Stmt\Global_ and write a nice notice message.
2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with global and one without (again look at the existing ones for statements)

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by micheleorselli** [comment]
Hi @ddmler, may I take care of that?

**Comment by ddmler** [comment]
@micheleorselli sure

**Comment by ddmler** [comment]
closed - merged with #213
