### ISSUE TITLE
[Analyzer] Don't use Labels

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#160]
It's those labels for Goto:
```php
abc:
$a = 1;
```
So we need a statement analyzer for Label Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Change existing DoNotUseGoto (Goto Analyzer is here: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/DoNotUseGoto.php )
and register it to Stmt\Label and Stmt\Goto_ and write a nice notice message. Look at other existing analyzers to see how to register something to multiple Nodes)
2. Add a Test (analyze-fixtures directory): Change Goto analyzers test and add one for the label

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by nikhilsaldanha** [comment]
Can I give this a try?

**Comment by ovr** [comment]
@nikhilsaldanha 
Seems to be, you can try to implement this

**Comment by ddmler** [comment]
closed - got merged with PR from @nikhilsaldanha
