### ISSUE TITLE
[Analyzer] Don't use InlineHTML

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#161]
It's bad practice to use inline html.
So we need a statement analyzer for InlineHTML Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/DoNotUseGoto.php )
and register it to Stmt\InlineHTML and write a nice notice message.
2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with inline HTML and one without (again look at the existing ones for statements) (you have to put the inline html inside a method/function for it to work currently, see existing tests)

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by nikhilsaldanha** [comment]
I think I'll give this a shot

**Comment by ddmler** [comment]
closed - merged with PR 171
