### ISSUE TITLE
[Analyzer] Dont use static:: in final class

### ISSUE THREAD

**Issue by ovr** [ovr/phpsa#164]
Hey!

It's a probably easy task, so it's good for someone who is new to the project.

```php
final class A {
    public static function test1()
    {
    }

    public static function test2()
    {
        static::test1(); // It's an unexpected code, class is `final`!
    }
}
```

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Expression/ErrorSuppression.php )
and register it to `Expr\StaticCall` and write a nice notice message.

How to find:
- Catch that left side of `$expr` is `static`
- Get `$context->scopePointer`, check that it's a `ClassDefinition`
- Check that `ClassDefinition` is a `final` class

2. Add it to PHPSA\Analyzer\Factory (registerExpressionPasses)
3. Write Tests (analyze-fixtures directory): One example with static and one without (again look at the existing ones for expressions like ErrorSuppression) (the test class is at the top of this issue)

Check our Contribution Guide and create a pull request.
Thanks 🍰

**Comment by dsalcedo** [comment]
interesting 👍

**Comment by ddmler** [comment]
closed - got merged with 184
