### ISSUE TITLE
[Analyzer] One Property definition per line

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#165]
It notices on: `public $a, $b=1;` or something like that.
So we need a statement analyzer for Property Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/DoNotUseGoto.php )
and register it to Stmt\Property. Now:
Check that `$stmt->props` (array) contains more than one entry. If yes write a nice notice message, else return false.
2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with one property and one with 2 or more (again look at the existing ones for statements)

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by barroca** [comment]
I will take it.

**Comment by barroca** [comment]
Please verify on PR https://github.com/ovr/phpsa/pull/177
