### ISSUE TITLE
[Analyzer] Property definition default value

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#166]
It notices on: `public $a = null;` since null is the default value and therefore not needed here.
So we need a statement analyzer for PropertyProperty Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/GotoUsage.php )
and register it to Stmt\PropertyProperty. Now:
Check that `$stmt->default instanceof Node\Expr` (and it is therefore not null itself). 

If yes check that:
`$compiled = $context->getExpressionCompiler()->compile($stmt->default);` 
is of type NULL by:
`if ($compiled->getType() == CompiledExpression::NULL)`
If yes write a nice notice message (that null is not needed or something like that), else return false.

2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with equals null and without (again look at the existing ones for statements)
4. Write a chapter in docs/05_Analyzers.md (its sorted alphabetically)
5. Add to .phpsa.yml at the bottom a setting on true for this analyzer

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by deepvyas** [comment]
@ddmler how do we register the analyzer and test.

I always get the **Failed asserting that an array contains Array &0** error when i do a **make ci**

**Comment by ddmler** [comment]
@deepvyas sorry it's a bug. PropertyProperty can't be registered yet. I'll fix that

**Comment by deepvyas** [comment]
@ddmler  I get the same issue while registering For_ as well. Is there a specific way to register the analyzer or just adding it to array returned by **getStatementPasses** function in PHPSA\Analyzer\Factory.php does the job.

**Comment by ddmler** [comment]
@deepvyas 
Create your PR, I will look what's missing then.
Basically to register it you have to add the line For_::class to getRegister() method and in the Factory your analyzer class to getStatementPasses.

**Comment by ddmler** [comment]
closed - merged with 247
