### ISSUE TITLE
[Easy] Rename Methods

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#167]
So our testsuite has some dataProviders. All their names start with test and therefore get executed by phpunit but we don't need that.
Task: Rename all data providers to a good name that doesn't start with test. (don't forget to change the docblock of the tests they are used from)
You can check which of them need that by running in the project root:
`./vendor/bin/phpunit -v --report-useless-tests`

This will output all methods that don't assert anything (the dataprovider methods)

Thanks :cake:

**Comment by DailyMatters** [comment]
@ddmler Can I get this?

**Comment by ddmler** [comment]
@DailyMatters sure.

**Comment by DailyMatters** [comment]
Great, thank you, will tackle this as soon as I get home.

**Comment by DailyMatters** [comment]
@ddmler 
I was thinking renaming the files by changing the 'test' part to 'dp_'. So 'testConcatResultStringDataProvider' would be 'dp_concatResultString'. What do you think? Is it clear enough?

**Comment by ddmler** [comment]
@DailyMatters would be better to rename it to something like "concatResultStringDataProvider" (because of naming conventions no _ ) Or in case of Concat it would be ok to "concatDataProvider" (since concats result is always string)

**Comment by DailyMatters** [comment]
Got it, thanks!
