### ISSUE TITLE
\ PHPSA\AliasManager::add and isClassImported aren't complementary to each other

### ISSUE THREAD

**Issue by DannyvdSluijs** [ovr/phpsa#173]
At https://github.com/ovr/phpsa/blob/master/src/AliasManager.php#L51 the namespace is added to the aliases array using numerical indexes, where is the isClassImported checks for the namespace to be available as a key.

This was discovered during writing the UT mentioned in #170 .

**Comment by ddmler** [comment]
We should change isClassImported to use numerical indexes then. :+1:

**Comment by DannyvdSluijs** [comment]
Will create a fix today or tomorrow
