### ISSUE TITLE
[Analyzer] Return and Yield in one Method

### ISSUE THREAD

**Issue by ovr** [ovr/phpsa#185]
So we need a statement analyzer for ClassMethod Node.
It's easy, so it's good for someone who is new to the project.

Referenced snippet

``` php
function test ($a) {
    if ($a) {
        return true;
    }

    yield false;
}
```

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/DoNotUseGoto.php )
and register it to Stmt\ClassMethod
https://github.com/ovr/phpsa/pull/186 review this PR fist, it a help PR for this issue contributors
What we need:
- We should that one Return at least exists
- Next check Yeild
- Notice about this
- Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
- Write Tests (analyze-fixtures directory): One example with equals null and without (again look at the existing ones for statements)
- Write a chapter in docs/05_Analyzers.md (its sorted alphabetically)
- Add to .phpsa.yml at the bottom a setting on true for this analyzer

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by ddmler** [comment]
closed - merged with 263
