### ISSUE TITLE
[Analyzer] Stupid unary operator

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#204]
UnaryPlus + positive number

```php
$a = +1;
$a = +1.0;
$a = +true;
```

think about: maybe change multiple unary analyzer to be a stupid unary analyzer and put both together or make a new analyzer.

**Comment by ovr** [comment]
> think about: maybe change multiple unary analyzer to be a stupid unary analyzer and put both together or make a new analyzer.

I suggest to split this, it's a yet another Analyzer
