### ISSUE TITLE
[Bug] Fileparser creates multiple functions from 1 ast

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#212]
@ovr 
When parsing:

``` php
class A {}
function b() {}
```

this creates 1 classdefinition & 2 functiondefinitions
all analyzers get called on both functiondefinitions so we get 2 times the message no docblock found for function b.

The problem is here:
https://github.com/ovr/phpsa/blob/a7bf656771a50eaaf3e299bd407fe0745178e408/src/Definition/FileParser.php#L89

by passing the complete astTree we pass 2 times the same function for parsing.

**Comment by ovr** [comment]
Thanks, I will take a look

**Comment by ovr** [comment]
@ddmler This issues should be fixed? Can you try again with latest `master` branch?
Thanks

**Comment by ddmler** [comment]
Yes it's fixed :+1:  Thanks
