### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sergeyklay** [ovr/phpsa#214]
Hello,

Current milestone is outdated

![phpsa](https://cloud.githubusercontent.com/assets/1256298/19219451/3058fcb0-8e1c-11e6-863c-9b653f8efe6a.png)

How about new release (stable, tagged version)?

**Comment by ddmler** [comment]
Would be great if we get configuration, interface compile (both PR from K-Phoen) merged for that.
Also the missing namespace support is a very important thing that's still missing (we get a million debug lines for that in travis)

**Comment by sergeyklay** [comment]
I suggest at least actualize the milestone. 
The same in projects:
![phpsa-1](https://cloud.githubusercontent.com/assets/1256298/19222254/e093e794-8e5c-11e6-930e-be41036b44e6.png)

**Comment by ovr** [comment]
PHP still in alpha version, after review/merge Configuration will make a tag, 0.6.0

**Comment by sergeyklay** [comment]
Thanks
