### ISSUE TITLE
[Analyzer] Static variable usage

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#215]
It's bad practice to use static $a; or something like that.
(This is not class static but variable static, see: http://php.net/manual/en/language.variables.scope.php )
So we need a statement analyzer for Static_ Node.
It's very easy, so it's good for someone who is new to the project.

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/GlobalUsage.php )
and register it to Stmt\Static_ and write a nice notice message.
2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with static and one without (again look at the existing ones for statements)

Check our Contribution Guide and create a pull request.
Thanks :cake:

**Comment by dmaicher** [comment]
I will look into this and prepare a PR :blush:

**Comment by dmaicher** [comment]
Here is the PR :wink: https://github.com/ovr/phpsa/pull/216

**Comment by ddmler** [comment]
closed - merged in 216
