### ISSUE TITLE
[Analyzer] Avoid octal, hexadecimal, binary

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#221]
First we need to create a possibility to register an analyzer to Node\Scalar
Then create an analyzer for Node\Scalar\LNumber
and check the KIND constants.
Example:
`$a = 0x12;`

**Comment by nikhilsaldanha** [comment]
I would like to try this out

**Comment by ddmler** [comment]
@nikhilsaldanha it's not yet possible to register an analyzer to Node\Scalar you would have to add this too.

**Comment by ddmler** [comment]
closed - merged with 251
