### ISSUE TITLE
[Command] New Compiler Command

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#223]
I was thinking the Compiler is pretty useful in itself. So how about we add a new Command "compile" that only runs the compiler (no analyzer) and therefore only reports syntax and language level errors?
The "check" command would be unaffected and run compiler and all analyzers. 

What do you guys think?

**Comment by ovr** [comment]
I think, this will be rly cool 👍 
Pretty simple code will work as expected/actual on PHP!
