### ISSUE TITLE
[Analyzer] For multiple conditions

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#233]
Simple Task: Statement Analyzer for For_ Node.
It should notice on:
```php
for($i=0, $j=0; $i<3, $j<2;$i++,$j++){
    echo "test"; // 2 times
}
```

How to do it:
1. Create Analyzer (you can use this one as a template: https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/Statement/GotoUsage.php )
and register it to Stmt\For_. Now:
Check that `count($stmt->cond) > 1`

If yes write a nice notice message (that you should merge the conditions into one with `&&`), else return false.

2. Add it to PHPSA\Analyzer\Factory (registerStatementPasses)
3. Write Tests (analyze-fixtures directory): One example with the code at the top and one with only 1 condition in for (normal for loop) (again look at the existing ones for statements)
4. Write a chapter in docs/05_Analyzers.md (its sorted alphabetically)
5. Add to .phpsa.yml at the bottom a setting on true for this analyzer

Check our Contribution Guide and create a pull request.

Thanks :cake:

**Comment by nikolaykovenko** [comment]
Hello, @ddmler. The task is very good analyzed and described, so I think it's a good starting point for my first pool request. So, if you don't mind, I can't implement this feature.

**Comment by ddmler** [comment]
@nikolaykovenko Would be awesome. I added another step to the issue, if you can do that too. (it's a hidden file if you don't see it in project directory) Ask if you need any help.

**Comment by nikolaykovenko** [comment]
Ok, great, thanks. So I start working, and I'll ask you if I need some help.

**Comment by ddmler** [comment]
closed - merged in 243
