### ISSUE TITLE
[Command] Create analyzer doc command

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#241]
We have a command "dump-reference" which dumps the default configuration.
I would suggest we rename this to dump-config and create a new one dump-docs or something like that, which dumps docs/05_Analyzers.md

It should just get every analyzer description (maybe sort them alphabetically) and dump them the same way the documentation file is structured right now. Maybe if an analyzer has a minimum php version add a sentence behind the description like "Disabled for PHP version config <= x"

**Comment by ovr** [comment]
Looks like implemented by @ddmler :) going to close it
