### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by funivan** [ovr/phpsa#26]
Hi. Your library is great. I can make some validations. 
But is is hard for me to understand structure of your library. 
For example i want to create "Missing @return keyword"   but I don’t know where i should place validation class. 
Other thing is interface. 
One class declared as  `class Statement {` other `class Mod extends AbstractExpressionCompiler`
possible it will be useful to create single interface and then extend it. 

P.S. Take a loot for php-cs-fixer they have each checker in separate file.

**Comment by ovr** [comment]
Hey!

> For example i want to create "Missing @return keyword" but I don’t know where i should place validation class. 

About analyzers, this will be implemented soon, maybe in 1 month
I am working on this now

Буду отдельно анализаторы (как сущьность), а текущий код я вынесу из Visitor - которые как раз Compiler станут

Это еще прототип, скоро будет очень много новых фишек)

**Comment by ovr** [comment]
@funivan 
https://github.com/ovr/phpsa/blob/master/src/Analyzer/Pass/FunctionCall/RandomApiMigration.php
