### ISSUE TITLE
[Analyzer] Nested Ternary

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#267]
Check for something like this:
```php
$x = ($a == 1) ? 2 : (($b == 2) ? 3 : 4);
```

and notice:
`Nested ternary operators can be confusing. Use if/elseif instead.`

**Comment by ovr** [comment]
Implemented by @ddmler in https://github.com/ovr/phpsa/pull/275/commits/8fc0ecf963cab86a1e1b598c50fbfb88aadd87c9
