### ISSUE TITLE
[Config][Question] No option for ArrayDimFetch (array_dim_fetch_on_non_array)?

### ISSUE THREAD

**Issue by hipio** [ovr/phpsa#276]
It seems that I cannot enable or disable the `array_dim_fetch_on_non_array` future of this tool, is this correct? I tried disabling `array_illegal_offset_type` as that is the only class that contains a reference to ArrayDimFetch, but that didn't disable the analysis. 

**Things I've tried to disable the analysis:**
- Add `array_dim_fetch` to the config
  - This resulted in an error (`  Unrecognized option "array_dim_fetch" under "phpsa.analyzers"`)
- Disable all the array related actions
- Disable all analyzers

I did look through the codebase and I know that the config is handled by the `Analyzer/Factory`-class but I can't figure out where to go from there.

**Comment by ddmler** [comment]
Hi since PHP would create an Error/Warning/Notice message for those, we are moving those into the compiler. However the compiler issues can not be disabled at the moment (I will add this very soon)
Thanks for pointing it out.

**Comment by hipio** [comment]
@ddmler Ah okay, thanks a lot for replying! Is this also the case for `mcall.static`? I tried to disable that as well to no avail, haha.

**Comment by ddmler** [comment]
Yes everything that has no key in the config at the moment will be renamed to language_error and gets a new config setting in the next few days hopefully

**Comment by ddmler** [comment]
@hipio PR is waiting for review. With it you can disable everything except syntax-error. You can clone the branch if you want to use it right now.

**Comment by ovr** [comment]
@hipio Merged in `master` by https://github.com/ovr/phpsa/commit/c54facd476aee889252c9d1128c96e168750039a, implemented by @ddmler

**Comment by hipio** [comment]
@ovr So we currently have one option that deals with everything, correct? Will this be changed in the future, as I do not want to disable all of the language checks, just a few of them because of false-positives. 😛

**Comment by ddmler** [comment]
I would like to change those checks so when we have a type of unknown we don't notice anything.
Currently whenever something is type unknown it notices for example "can't fetch from non-array" or something like that. We should only notice if we are sure of it.

**Comment by ddmler** [comment]
closed - see #298 for false positive reduction work
