### ISSUE TITLE
[Analyzer] Check duplicated variables in use

### ISSUE THREAD

**Issue by ovr** [ovr/phpsa#279]
```php
$a = 1;
$b = 2;

function () use ($a, $b, $a) { // <- duplicated variable $a
} 
```

**Comment by Kilgaloon** [comment]
Is this still open? Somebody were doing something on this one?

**Comment by ovr** [comment]
@Kilgaloon As I known it's still open, can you check it? Thank!

**Comment by Kilgaloon** [comment]
I will start working on this. Somebody can maybe take a look at PR related to #329

**Comment by ovr** [comment]
I am going to close this issue becase it's implemented by @Kilgaloon
