### ISSUE TITLE
Regular expressions check

### ISSUE THREAD

**Issue by EmanueleMinotto** [ovr/phpsa#28]
https://github.com/marcioAlmada/regex-guard

Could this project be interesting for an integration into phpsa?

**Comment by ovr** [comment]
@EmanueleMinotto 
Yeap, I saw it before, This will helpfull with awesome regex check
Than you for notify about it

For now I am working on first alpha release with stable core :)

**Comment by ddmler** [comment]
i think this is done @ovr

**Comment by ovr** [comment]
@ddmler Thank for notice, I am going to close, because as you said, it's done :)
