### ISSUE TITLE
[Bug] Unused variable when used in string literal as method argument

### ISSUE THREAD

**Issue by Kilgaloon** [ovr/phpsa#280]
So basically this:

    $name="John Doe";
    Class::method("Hello $name");

This throws warning that variable is unused, but clearly it is.

**Comment by ovr** [comment]
This bug is caused because We didn't support template strings...

**Comment by Kilgaloon** [comment]
It would be nice to have it then.

**Comment by ovr** [comment]
@Kilgaloon looks like you case was fixed, can you try latest master changes?
Thanks

**Comment by Kilgaloon** [comment]
Ye, you can close this issue

**Comment by ovr** [comment]
@Kilgaloon Thank for bag reporting and testing 👍 
Going to close this issue because fixed in https://github.com/ovr/phpsa/commit/795841bee687f086ae84ef0b35519514fa11790a

Thanks
