### ISSUE TITLE
[Compiler] Type 'float' support(PHP7.0)

### ISSUE THREAD

**Issue by algo13** [ovr/phpsa#289]
[Type declarations](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration)

```php
<?php
function f(float $f)
{
    echo 'test';
}
```

```
  [RuntimeException]
  Type 'float' is not supported
```

**Comment by ovr** [comment]
@algo13 Thank for bug report, fixed in `master` branch!
