### ISSUE TITLE
[Bug] Apply BitwiseNot to null

### ISSUE THREAD

**Issue by algo13** [ovr/phpsa#292]
```php
<?php
function f(int $flag)
{
    return ~$flag;
}
```

```php
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Unsupported operand types
```

[value is null](https://github.com/ovr/phpsa/blob/c11045f9be963903f79dc2323737ec5a912f94f1/src/Compiler/Expression/Operators/Bitwise/BitwiseNot.php#L28)

```
object(PHPSA\CompiledExpression) {
  ["type"]=> string(7) "integer"
  ["value"]=> NULL
}
```

**Comment by ovr** [comment]
@algo13 Issue about BitwiseNot operator should be fixed, but I am going to review another operators, they can be not safety
