### ISSUE TITLE
Build a phar package for easier integration with CI tools

### ISSUE THREAD

**Issue by kalessil** [ovr/phpsa#3]
Php CS fixer, PhpUnit and others are providing this kind of package and it's very handy when integrating those tools into CI-infrastructure.

**Comment by ovr** [comment]
Thank you for this idea
I will mark  issue as enhancement and I will do it on first ALPHA version
For now project is pre-pre-pre-pre-pre-pre alpha :)

**Comment by ovr** [comment]
Implemented, continue to work on pre alpha version
