### ISSUE TITLE
[Bug] False positive ArrayDimFetch for SplObjectStorage

### ISSUE THREAD

**Issue by algo13** [ovr/phpsa#307]
[ArrayDimFetch.php](https://github.com/ovr/phpsa/blob/9de304d74d0791b980d5b602bf703d35e480cd4e/src/Compiler/Expression/ArrayDimFetch.php#L26)

```php
function f()
{
    $o = new \stdClass;
    $obj = new \SplObjectStorage;
    $obj[$o] = 1;
    echo $obj[$o]; //< Notice:  It's not possible to fetch an array element on a non array [language_error]
}
```

**Comment by ddmler** [comment]
when checking this code i also get:

Unimplemented PhpParser\Node\Stmt\Echo_

Notice:  Illegal array offset type object for key $o. in x on 9 [array.illegal_offset_type]
$obj[$o] = 1;

**Comment by algo13** [comment]
@ddmler Thanks for comment.

[array.illegal_offset_type] is false positive too.

https://3v4l.org/v5l8f
http://php.net/manual/class.splobjectstorage.php

**Comment by algo13** [comment]
@ovr Thanks for [commit \(\[ControlFlowGraph\] Dont use echo, use debug from Context\)](https://github.com/ovr/phpsa/commit/f8b546ca38d78065aa5abfe21fe71d97374b3df3)

`echo 'Unimplemented'` ([ControlFlowGraph.php#L109](https://github.com/ovr/phpsa/blob/f8b546ca38d78065aa5abfe21fe71d97374b3df3/src/ControlFlow/ControlFlowGraph.php#L109))


overlook?

**Comment by ovr** [comment]
Sure, I fixed this notice

```
Unimplemented PhpParser\Node\Stmt\Echo_
```

Because CFG in initial state and it's not a good idea to write it without debug check

**Comment by algo13** [comment]
@ovr After your fixed, `echo` is left only [ControlFlowGraph.php#L109](https://github.com/ovr/phpsa/blob/f8b546ca38d78065aa5abfe21fe71d97374b3df3/src/ControlFlow/ControlFlowGraph.php#L109).

Is not it `$this->context->debug()` ? ;)
