### ISSUE TITLE
[Bug] Unimplemented output in tests

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#322]
when running make tests we get "Unimplemented PhpParser\Node\Stmt\Echo_" as output in one of the tests.

**Comment by ovr** [comment]
Thanks for bug report @ddmler, I miss the second `echo` inside `ControlFlowGraph` in https://github.com/ovr/phpsa/commit/f8b546ca38d78065aa5abfe21fe71d97374b3df3
