### ISSUE TITLE
[Analyzer] printf format string and parameters

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#329]
<p>Create an analyzer that checks printf/sprintf and similar function calls for: format string has same number of placeholders as parameters are passed into it. (And maybe that the types are correct)</p>

**Comment by Kilgaloon** [comment]
Maybe i can jump on this one. I will see what can i do in following days

**Comment by Kilgaloon** [comment]
Currently analyzer checks is first argument string, is type format valid and length of type formats in string vs array of arguments passed for printf/sprintf and number of arguments passed for sprintf
