### ISSUE TITLE
Upgrade nikic/php-parser to 3 for PHP 7.1 support

### ISSUE THREAD

**Issue by phaldan** [ovr/phpsa#332]
Currently phpsa depends on version 2 of nikic/php-parser, which supports only PHP 5.2 to PHP 7.0.
For a proper PHP 7.1 support you should consider to upgrade to version 3 of nikic/php-parser.

**Comment by ddmler** [comment]
Hi @phaldan we already use php-parser version 3 in the master branch. So the next release includes PHP 7.1 support.

Thanks
