### ISSUE TITLE
Fatal error: Uncaught TypeError

### ISSUE THREAD

**Issue by EvgenyOrekhov** [ovr/phpsa#353]
When I run `vendor/bin/phpsa check` I get the following error:

```text
Fatal error: Uncaught TypeError: Argument 1 passed to PHPSA\Configuration::__construct() must be of the type array, null given, called in /app/vendor/ovr/phpsa/src/Command/AbstractCommand.php on line 48 and defined in /app/vendor/ovr/phpsa/src/Configuration.php:34
Stack trace:
#0 /app/vendor/ovr/phpsa/src/Command/AbstractCommand.php(48): PHPSA\Configuration->__construct(NULL, Array, NULL)
#1 /app/vendor/ovr/phpsa/src/Command/CheckCommand.php(75): PHPSA\Command\AbstractCommand->loadConfiguration('.phpsa.yml', '/app')
#2 /app/vendor/symfony/console/Command/Command.php(252): PHPSA\Command\CheckCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(865): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Obj in /app/vendor/ovr/phpsa/src/Configuration.php on line 34
```

I don't have a .phpsa.yml in my project. Do I need one? Should PHPSA work without a .phpsa.yml?

**Comment by EvgenyOrekhov** [comment]
PHPSA version: e2d3e118d289e5ab66dab23cb2af0cd1cc2e9e09
PHP version: 7.2.2
symfony/* packages version: 4.0.4

**Comment by ddmler** [comment]
You do need a .phpsa.yml file. If you don't have one yourself it should use the one in the root project directory. Did you delete that one or is it broken?

**Comment by EvgenyOrekhov** [comment]
@ddmler This is how I got fatal error:

1. `composer require --dev ovr/phpsa:dev-master`
2. `vendor/bin/phpsa check`

What did I do wrong?

**Comment by ddmler** [comment]
I tried your steps, it's a bug in finding the location of the config file here:
https://github.com/ovr/phpsa/blob/master/src/Command/AbstractCommand.php#L38
both supplied file locations here are your project root directory, we need one that looks inside our vendor/ovr/phpsa folder.

**Comment by armoour** [comment]
i met this issue too.

**Comment by EvgenyOrekhov** [comment]
I am no longer interested in this. Feel free to reopen if needed.
