### ISSUE TITLE
New analyzer - use argument unpacking (...) instead of func_get_args()

### ISSUE THREAD

**Issue by ovr** [ovr/phpsa#53]
To implement it We need to complete task:

Find function by name with func_get_args, example Pass\Expression\FunctionCall\*

Next We need to asert that `scopePointer` from `Context` is a method or function
After it Wee need to assert that parameters count is 0

Example that We need to detect and suggest
```php
class Test {
    public function test() // NO PARAMETERS
    {
           return func_get_args();
    }
}
```

When we cant suggest another way

```php
class Test {
    public function test($a, $b, $c) // SOME PARAMETERS
    {
           return func_get_args();
    }
}
```

**Comment by ovr** [comment]
Hey!

I added a small description for this task
seems this probably easy to implement
If it's not clear, ask me questions about this task

/c @rocketpastsix

Thanks 🍰

**Comment by rocketpastsix** [comment]
yea Ill take a look at it. cheers!

**Comment by ovr** [comment]
About `$scopePointer`,

After find function a call to `func_get_args`, you can get `scopePointer`:

```php
/** @var Defintion\ClassMethod|Defintion\FunctionDefintion $scopePointer */
var_dump($scopePointer = $context->scopePointer->getObject());
```

**Comment by ovr** [comment]
Implemented by @ddmler 👍
