### ISSUE TITLE
Advice for Disabling XDebug at Runtime

### ISSUE THREAD

**Issue by dragoonis** [ovr/phpsa#56]
Your documentation doesn't need to tell people to disable xdebug, it can be disabled for the particular run.

```php -n -d xdebug.enable=0 -f bin/phpsa```

If you don't want to apply -d params you can disable xdebug by calling ```xdebug_disable()``` which as per this link you will see it updated the zend_error_cb callback to the system default one instead of xdebug's - http://lxr.php.net/xref/PECL/xdebug/xdebug.c#2353

**Comment by ovr** [comment]
Thank you for notice 👍 🍰 
Anyway `xdebug_disable ` will disable only callback error/exceptions handler, I've added a code to disable it and update README with notice about how to disable

Thanks
