### ISSUE TITLE
[Analyzer] Deprecated Functions

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#63]
Create an Analyzer which checks for usage of (in newer versions) deprecated functions. So if we check a PHP 5.5 script we get all warnings for php7 deprecations too.

We should add a configuration to turn this off.

for example this RFC passed: https://wiki.php.net/rfc/mcrypt-viking-funeral

So Mcrypt will be deprecated. Our Analyzer could recommend the use of paragonie/halite (or libsodium) instead.

**Comment by ovr** [comment]
So, I introduce a configuration system, still working on it (disable/enable passes) and target platform (PHP 5.6, 7.0, 7.1)
Will push ASAP this feature

**Comment by ddmler** [comment]
This issue can be closed what's missing is the configuration, which is issue #39
