### ISSUE TITLE
[Bug] UseCast Analyzer intval 2 arguments

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#78]
While checking a file with ./bin/phpsa which has something like:
`intval(1,2);`
we get this error:
PHP Notice:  Undefined offset: 1 in ...phpsa/vendor/ovr/phpreflection/src/FunctionReflection.php on line 160

This error only occurs when intval has 2 arguments.
`intval(1);`
works fine.

**Comment by ovr** [comment]
Reproduced and fixed, check it by

```sh
git pull origin master
composer update
```

Thanks

**Comment by ovr** [comment]
ping @ddmler

**Comment by ddmler** [comment]
:+1: works. i will add a test later for this.
