### ISSUE TITLE
[Bug] Calling parent constructor

### ISSUE THREAD

**Issue by ddmler** [ovr/phpsa#97]
When using
`parent::__construct();`
we get a notice from phpsa: method __construct() is not static but was called as static way

this is however the right way to call the parent constructor (and destructor)

**Comment by ovr** [comment]
Fixed by @K-Phoen in https://github.com/ovr/phpsa/pull/131
In `master` by https://github.com/ovr/phpsa/commit/2e4f70404cecd5ef6a413b250944abfd82e8cb54
